#!/bin/sh

if [ "$1" == "" ]; then
	echo "Usage: $0 <host> [make options]"
	exit 1
fi

SELF=`hostname`
HOST=$1
LOCAL="`pwd`"
DIRNAME="`basename "$LOCAL"`"
REMOTE="${SELF}/${DIRNAME// /\\ }"

shift

if [ "$HOST" == "bbb" ]; then
	ssh $HOST date -s @`( date -u +"%s" )`
fi

ssh $HOST "mkdir -p ${REMOTE}"
rsync -avz --delete --exclude=.git --exclude-from=.gitignore "${LOCAL}/" "${HOST}:${REMOTE}/"
ssh $HOST "cd ${REMOTE} && make $*"
